name: New Client Broker
on:
  push:
    branches:
      - test-new-client

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
  S3_BUCKET: ${{ secrets.DEV_CODEDEPLOY_S3_BUCKET }}
  APPLICATION_NAME: ${{ secrets.APPLICATION_NAME }}
  DEPLOYMENT_GROUP: ${{ secrets.DEV_DEPLOYMENT_GROUP }}


jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Zip Contents
      run: |
        sudo chmod +x docker-entrypoint.sh
        zip -r build.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_DEFAULT_REGION}}

    - name: Upload
      id: upload
      uses: Lishenga/aws-code-deploy@v1
      with:
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        COMMAND: 'upload'
        ZIP_FILE: 'build.zip'

    - name: Deploy
      id: deploy
      uses: Lishenga/aws-code-deploy@v1
      with:
        AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
        APPLICATION_NAME: ${{ env.APPLICATION_NAME }}
        DEPLOYMENT_GROUP: ${{ env.DEPLOYMENT_GROUP }}
        S3_BUCKET: ${{ env.S3_BUCKET }}
        COMMAND: 'deploy'
        WAIT: 'true'
        IGNORE_APPLICATION_STOP_FAILURES: 'true'
        FILE_EXISTS_BEHAVIOR: 'OVERWRITE'